#!/usr/bin/env python3
"""Keja AI Platform Technical Audit - ~100 page ReportLab body PDF builder.

Follows briefs/report.md:
- TocDocTemplate + multiBuild (auto TOC with clickable links)
- Cascade palette (seed 42) - no hand-picked colors
- FreeSerif family for English body; DejaVuSans (mono) for code
- install_font_fallback() called after registration
- All table cells wrapped in Paragraph(); colWidths from ratios x available width
- CondPageBreak(25%) before H1 only (no forced page breaks between chapters)
- safe_keep_together() with 40% page-height cap
- Charts embedded via embed_image() preserving aspect ratio
Output: body PDF (no cover; cover generated separately via html2poster.js).
"""
import os, sys, hashlib

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
_scripts = os.path.join(PDF_SKILL_DIR, 'scripts')
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, Image, KeepTogether, CondPageBreak,
                                HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

# ---------------------------------------------------------------- fonts
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ---------------------------------------------------------------- palette
# Cascade Palette (auto-generated by design_engine.py palette-cascade, seed 42)
PAGE_BG       = colors.HexColor('#f4f5f5')
SECTION_BG    = colors.HexColor('#f0f1f2')
CARD_BG       = colors.HexColor('#e8eaeb')
TABLE_STRIPE  = colors.HexColor('#ebeded')
HEADER_FILL   = colors.HexColor('#32454e')
COVER_BLOCK   = colors.HexColor('#566a74')
BORDER        = colors.HexColor('#acbdc5')
ICON          = colors.HexColor('#4b86a4')
ACCENT        = colors.HexColor('#1f6c92')
ACCENT_2      = colors.HexColor('#c23a50')
TEXT_PRIMARY  = colors.HexColor('#131515')
TEXT_MUTED    = colors.HexColor('#747b7e')
SEM_SUCCESS   = colors.HexColor('#529067')
SEM_WARNING   = colors.HexColor('#8c7443')
SEM_ERROR     = colors.HexColor('#a25b54')
SEM_INFO      = colors.HexColor('#507aa4')
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_ODD      = TABLE_STRIPE

# ---------------------------------------------------------------- geometry
PAGE_W, PAGE_H = A4
MARGIN   = 0.95 * inch
AVAIL_W  = PAGE_W - 2 * MARGIN
AVAIL_H  = PAGE_H - 2 * MARGIN
MAX_KEEP = AVAIL_H * 0.4
H1_COND  = AVAIL_H * 0.25

DOC_TITLE  = 'Keja AI Platform Technical Audit'
DOC_AUTHOR = 'Keja AI Engineering Audit Team'
ASSETS = os.path.join(HERE, 'assets')

# ---------------------------------------------------------------- styles
S = {}
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                           alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                           spaceBefore=0, spaceAfter=8)
S['lead'] = ParagraphStyle('Lead', parent=S['body'], fontSize=11, leading=17.5,
                           textColor=TEXT_PRIMARY, spaceAfter=10)
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=21, leading=26,
                         textColor=HEADER_FILL, spaceBefore=6, spaceAfter=4,
                         alignment=TA_LEFT)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14.5, leading=19,
                         textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
S['h3'] = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=15.5,
                         textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
S['bullet'] = ParagraphStyle('Bullet', parent=S['body'], alignment=TA_LEFT,
                             leftIndent=16, bulletIndent=4, spaceAfter=4)
S['numbered'] = ParagraphStyle('Numbered', parent=S['body'], alignment=TA_LEFT,
                               leftIndent=20, bulletIndent=4, spaceAfter=5)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                              textColor=TEXT_MUTED, alignment=TA_CENTER,
                              spaceBefore=3, spaceAfter=6)
S['quote'] = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5,
                            leading=16, textColor=HEADER_FILL, leftIndent=24,
                            rightIndent=12, spaceBefore=8, spaceAfter=8)
S['callout'] = ParagraphStyle('Callout', fontName='FreeSerif', fontSize=10, leading=15.5,
                              textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['stat_big'] = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=19, leading=23,
                               textColor=ACCENT, alignment=TA_CENTER)
S['stat_label'] = ParagraphStyle('StatLabel', fontName='FreeSerif', fontSize=8.5,
                                 leading=11.5, textColor=TEXT_MUTED, alignment=TA_CENTER)
S['th'] = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.2, leading=12,
                         textColor=colors.white, alignment=TA_LEFT)
S['td'] = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.2, leading=12.5,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
S['td_c'] = ParagraphStyle('TDC', parent=S['td'], alignment=TA_CENTER)
S['td_b'] = ParagraphStyle('TDB', parent=S['td'], fontName='FreeSerif-Bold')
S['code'] = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8.2, leading=11.8,
                           textColor=HEADER_FILL, backColor=SECTION_BG,
                           leftIndent=8, rightIndent=8, spaceBefore=0, spaceAfter=0,
                           alignment=TA_LEFT, borderPadding=6)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=21, leading=26,
                                textColor=HEADER_FILL, spaceAfter=14)
S['part'] = ParagraphStyle('Part', fontName='FreeSerif', fontSize=12, leading=16,
                           textColor=ACCENT, spaceBefore=2, spaceAfter=10)

# ---------------------------------------------------------------- doc template
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text  = getattr(flowable, 'bookmark_text', '')
            key   = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def _header_footer(canvas, doc):
    canvas.saveState()
    # header
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - MARGIN + 22, DOC_TITLE.upper())
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - MARGIN + 14, PAGE_W - MARGIN, PAGE_H - MARGIN + 14)
    # footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, MARGIN - 18, PAGE_W - MARGIN, MARGIN - 18)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, MARGIN - 30, DOC_AUTHOR)
    canvas.drawRightString(PAGE_W - MARGIN, MARGIN - 30, str(doc.page))
    canvas.restoreState()

# ---------------------------------------------------------------- helpers
def add_heading(text, style, level=0):
    key = 'h_' + hashlib.md5((str(level) + text).encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text.replace('<b>', '').replace('</b>', '')
    p.bookmark_key = key
    return p

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        try:
            w, h = el.wrap(AVAIL_W, AVAIL_H)
            total_h += h
        except Exception:
            return list(elements)
    if total_h <= MAX_KEEP:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def embed_image(path, max_width=None, max_height=None):
    if max_width is None:
        max_width = AVAIL_W
    if max_height is None:
        max_height = A4[1] * 0.34
    pil = PILImage.open(path)
    ow, oh = pil.size
    # PNGs are rendered at 2x (200dpi); display at ~half scale capped by box
    ratio = min(max_width / ow, max_height / oh)
    return Image(path, width=ow * ratio, height=oh * ratio)

def make_table(spec):
    """spec: {cols: [ratios], header: [...], rows: [[...]], align: 'l'/'c' per col,
              font: 9.2, header_font, caption}"""
    ratios = spec['cols']
    widths = [r * AVAIL_W for r in ratios]
    assert abs(sum(ratios) - 1.0) < 0.01, 'ratios must sum to 1'
    align = spec.get('align', ['l'] * len(ratios))
    fs = spec.get('font', 9.2)
    th = ParagraphStyle('th_x', parent=S['th'], fontSize=fs, leading=fs + 2.8)
    td = ParagraphStyle('td_x', parent=S['td'], fontSize=fs, leading=fs + 3.3)
    td_c = ParagraphStyle('tdc_x', parent=td, alignment=TA_CENTER)
    data = [[Paragraph('<b>%s</b>' % h, th) for h in spec['header']]]
    for row in spec['rows']:
        cells = []
        for j, cell in enumerate(row):
            sty = td_c if align[j] == 'c' else td
            if isinstance(cell, str) and cell.startswith('**') and cell.endswith('**'):
                cells.append(Paragraph('<b>%s</b>' % cell[2:-2], sty))
            else:
                cells.append(Paragraph(str(cell), sty))
        data.append(cells)
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4.5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      colors.white if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    return t

def make_callout(text):
    p = Paragraph(text, S['callout'])
    t = Table([[p]], colWidths=[AVAIL_W * 0.96])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 9),
    ]))
    return t

def make_stats(stats):
    """stats: list of (value, label) - render as a single row of stat cards."""
    n = len(stats)
    cells = []
    for value, label in stats:
        inner = Table(
            [[Paragraph('<b>%s</b>' % value, S['stat_big'])],
             [Paragraph(label, S['stat_label'])]],
            colWidths=[AVAIL_W / n - 10])
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
            ('BOX', (0, 0), (-1, -1), 0.8, ACCENT),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
            ('TOPPADDING', (0, -1), (-1, -1), 2),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ]))
        cells.append(inner)
    outer = Table([cells], colWidths=[AVAIL_W / n] * n, hAlign='CENTER')
    outer.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
    ]))
    return outer

# ---------------------------------------------------------------- block DSL
FIG_COUNTER = {'n': 0}
TBL_COUNTER = {'n': 0}

def process_blocks(blocks, story):
    pending_heading = None  # keep heading with first following block
    for blk in blocks:
        kind = blk[0]
        el_list = []
        if kind == 'h2':
            el_list = [CondPageBreak(70), add_heading(blk[1], S['h2'], level=1)]
        elif kind == 'h3':
            el_list = [Paragraph('<b>%s</b>' % blk[1], S['h3'])]
        elif kind == 'body':
            el_list = [Paragraph(blk[1], S['body'])]
        elif kind == 'lead':
            el_list = [Paragraph(blk[1], S['lead'])]
        elif kind == 'bullet':
            for item in blk[1]:
                el_list.append(Paragraph(item, S['bullet'], bulletText='\u2022'))
            el_list.append(Spacer(1, 4))
        elif kind == 'numbered':
            for i, item in enumerate(blk[1], 1):
                el_list.append(Paragraph(item, S['numbered'], bulletText='%d.' % i))
            el_list.append(Spacer(1, 4))
        elif kind == 'callout':
            el_list = [Spacer(1, 6), make_callout(blk[1]), Spacer(1, 8)]
        elif kind == 'stats':
            el_list = [Spacer(1, 6), make_stats(blk[1]), Spacer(1, 10)]
        elif kind == 'quote':
            q = Table([[Paragraph(blk[1], S['quote'])]], colWidths=[AVAIL_W * 0.94])
            q.setStyle(TableStyle([
                ('LINEBEFORE', (0, 0), (0, -1), 2, BORDER),
                ('LEFTPADDING', (0, 0), (-1, -1), 14),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            el_list = [q, Spacer(1, 6)]
        elif kind == 'table':
            TBL_COUNTER['n'] += 1
            spec = blk[1]
            t = make_table(spec)
            cap = Paragraph('Table %d: %s' % (TBL_COUNTER['n'], spec['caption']), S['caption'])
            el_list = [Spacer(1, 10)]
            el_list += safe_keep_together([t, Spacer(1, 4), cap])
            el_list.append(Spacer(1, 10))
        elif kind == 'chart':
            FIG_COUNTER['n'] += 1
            fname, cap, max_h = blk[1], blk[2], blk[3] if len(blk) > 3 else 300
            img = embed_image(os.path.join(ASSETS, fname), max_width=AVAIL_W * 0.98,
                              max_height=max_h)
            capp = Paragraph('Figure %d: %s' % (FIG_COUNTER['n'], cap), S['caption'])
            el_list = [Spacer(1, 14)] + safe_keep_together([img, Spacer(1, 5), capp])
            el_list.append(Spacer(1, 14))
        elif kind == 'code':
            lines = blk[1].split('\n')
            paras = [Paragraph(l.replace(' ', ' ') if l else ' ', S['code'])
                     for l in lines]
            inner = Table([[p] for p in paras], colWidths=[AVAIL_W * 0.94])
            inner.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
                ('LINEBEFORE', (0, 0), (0, -1), 2, ICON),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('TOPPADDING', (0, 0), (-1, -1), 1),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
            ]))
            el_list = [Spacer(1, 6), inner, Spacer(1, 8)]
        elif kind == 'spacer':
            el_list = [Spacer(1, blk[1])]
        elif kind == 'divider':
            el_list = [Spacer(1, 4), HRFlowable(width='100%', color=BORDER,
                                                thickness=0.6), Spacer(1, 6)]
        if kind == 'h2' or kind == 'h3':
            pending_heading = el_list
            continue
        if pending_heading is not None:
            merged = pending_heading + el_list[:1]
            story.extend(safe_keep_together(merged))
            story.extend(el_list[1:])
            pending_heading = None
        else:
            story.extend(el_list)
    if pending_heading is not None:
        story.extend(pending_heading)

# ---------------------------------------------------------------- build
def build():
    from content_1 import CHAPTERS as C1
    from content_2 import CHAPTERS as C2
    from content_3 import CHAPTERS as C3
    from content_4 import CHAPTERS as C4
    from content_5 import CHAPTERS as C5
    from content_6 import CHAPTERS as C6
    from content_7 import CHAPTERS as C7
    from content_8 import CHAPTERS as C8
    all_chapters = C1 + C2 + C3 + C4 + C5 + C6 + C7 + C8

    out = os.path.join(HERE, 'body.pdf')
    doc = TocDocTemplate(out, pagesize=A4,
                         leftMargin=MARGIN, rightMargin=MARGIN,
                         topMargin=MARGIN + 0.18 * inch, bottomMargin=MARGIN,
                         title=DOC_TITLE, author=DOC_AUTHOR,
                         creator='Z.ai', subject='Phase 2 deep technical audit of the keja-ai repository')

    story = []
    # ---- TOC front matter
    story.append(Paragraph('<b>Table of Contents</b>', S['toc_title']))
    story.append(HRFlowable(width='100%', color=ACCENT, thickness=1.6, spaceAfter=12))
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle('TOC0', fontName='FreeSerif-Bold', fontSize=10.8, leading=15.5,
                       leftIndent=14, firstLineIndent=-14, spaceBefore=7,
                       textColor=TEXT_PRIMARY),
        ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=9.3, leading=13,
                       leftIndent=30, firstLineIndent=-14, spaceBefore=2,
                       textColor=TEXT_MUTED),
    ]
    toc.dotsMinLevel = 0
    story.append(toc)
    story.append(PageBreak())

    chapter_no = 0
    appendix_no = 0
    for ch in all_chapters:
        if ch.get('type') == 'appendix':
            appendix_no += 1
            title = 'Appendix %s: %s' % (chr(64 + appendix_no), ch['title'])
        else:
            chapter_no += 1
            title = '%d. %s' % (chapter_no, ch['title'])
        if ch.get('part'):
            story.append(CondPageBreak(H1_COND))
            story.append(Spacer(1, 10))
            story.append(Paragraph('<b>%s</b>' % ch['part'].upper(), S['part']))
        story.append(CondPageBreak(H1_COND))
        h = add_heading(title, S['h1'], level=0)
        rule = HRFlowable(width='100%', color=ACCENT, thickness=1.4,
                          spaceBefore=2, spaceAfter=12)
        blocks = list(ch['blocks'])
        # bind heading + rule + first block
        story.extend(safe_keep_together([h, rule]))
        process_blocks(blocks, story)
        story.append(Spacer(1, 16))

    doc.multiBuild(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    print('BODY BUILT:', out)

if __name__ == '__main__':
    build()
