#!/usr/bin/env python3
"""
keja_pdf_kit.py — shared ReportLab infrastructure for the Keja AI document
suite (5 PDFs, one visual system). Implements the pdf-skill Report brief:
cascade palette, FreeSerif typography, TocDocTemplate + multiBuild, safe
KeepTogether, Paragraph-wrapped tables, CalloutBox stats, Template-01 HUD
covers rendered via html2poster.js and merged with pypdf.
"""
import hashlib
import os
import subprocess
import sys

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily, stringWidth
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, Image, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

# ── Fonts (allowed set only) ────────────────────────────────────────────────
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
# NOTE: this image ships NotoSansSC only as a VARIABLE font, which ReportLab
# cannot consume — register the static Sarasa Mono SC under the "Noto Sans SC"
# key so the skill's fallback chain (FreeSerif -> NotoSerifSC -> Noto Sans SC)
# stays fully resolvable. The documents are English; this is CJK emergency cover.
pdfmetrics.registerFont(TTFont("Noto Sans SC", f"{FONT_DIR}/truetype/chinese/SarasaMonoSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("Noto Sans SC Bold", f"{FONT_DIR}/truetype/chinese/SarasaMonoSC-Bold.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
registerFontFamily("Noto Sans SC", normal="Noto Sans SC", bold="Noto Sans SC Bold")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")

from pdf import install_font_fallback  # noqa: E402  (skill helper)
install_font_fallback()

# ── Cascade palette (auto-generated by design_engine.py palette-cascade,
#    seed 7, mode minimal — copy-pasted, not hand-picked) ───────────────────
PAGE_BG       = colors.HexColor('#eff0f1')
SECTION_BG    = colors.HexColor('#f0f1f2')
CARD_BG       = colors.HexColor('#e4e7e8')
TABLE_STRIPE  = colors.HexColor('#ebedee')
HEADER_FILL   = colors.HexColor('#334650')
COVER_BLOCK   = colors.HexColor('#5a7886')
BORDER        = colors.HexColor('#b8c8cf')
ICON          = colors.HexColor('#52798c')
ACCENT        = colors.HexColor('#3681a6')
ACCENT_2      = colors.HexColor('#b43a4e')
TEXT_PRIMARY  = colors.HexColor('#1a1b1c')
TEXT_MUTED    = colors.HexColor('#6f7578')
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Geometry ────────────────────────────────────────────────────────────────
MARGIN = 0.9 * inch                      # symmetric, overflow.md §1.5
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN            # ≈ 465pt
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25               # pagination.md §4

# ── Styles (report.md component reference) ─────────────────────────────────
S = {}
S["body"] = ParagraphStyle("Body", fontName="FreeSerif", fontSize=10.5,
                           leading=17, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                           spaceBefore=0, spaceAfter=9)
S["lead"] = ParagraphStyle("Lead", parent=S["body"], fontSize=11.5, leading=19,
                           textColor=TEXT_PRIMARY, spaceAfter=12)
S["h1"] = ParagraphStyle("H1", fontName="FreeSerif", fontSize=22, leading=27,
                         textColor=HEADER_FILL, spaceBefore=18, spaceAfter=6)
S["h2"] = ParagraphStyle("H2", fontName="FreeSerif", fontSize=15, leading=20,
                         textColor=TEXT_PRIMARY, spaceBefore=16, spaceAfter=7)
S["h3"] = ParagraphStyle("H3", fontName="FreeSerif", fontSize=11.5, leading=16,
                         textColor=TEXT_PRIMARY, spaceBefore=12, spaceAfter=6)
S["bullet"] = ParagraphStyle("Bullet", parent=S["body"], alignment=TA_LEFT,
                             leftIndent=16, bulletIndent=4, spaceAfter=5)
S["numbered"] = ParagraphStyle("Numbered", parent=S["bullet"])
S["caption"] = ParagraphStyle("Caption", fontName="FreeSerif-Italic", fontSize=8.5,
                              leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED,
                              spaceBefore=3, spaceAfter=6)
S["quote"] = ParagraphStyle("Quote", fontName="FreeSerif-Italic", fontSize=10.5,
                            leading=17, leftIndent=24, textColor=TEXT_PRIMARY,
                            alignment=TA_LEFT, spaceBefore=10, spaceAfter=10)
S["code"] = ParagraphStyle("Code", fontName="DejaVuSans", fontSize=8.5, leading=12.5,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                           backColor=SECTION_BG, borderPadding=(6, 8, 6, 8),
                           leftIndent=8, spaceBefore=8, spaceAfter=10)
S["th"] = ParagraphStyle("TH", fontName="FreeSerif", fontSize=9.5, leading=13,
                         textColor=colors.white, alignment=TA_LEFT)
S["td"] = ParagraphStyle("TD", fontName="FreeSerif", fontSize=9.5, leading=13,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S["td_b"] = ParagraphStyle("TDB", parent=S["td"], fontName="FreeSerif-Bold")
S["stat"] = ParagraphStyle("StatBig", fontName="FreeSerif", fontSize=21, leading=25,
                           textColor=ACCENT, alignment=TA_CENTER)
S["stat_label"] = ParagraphStyle("StatLabel", fontName="FreeSerif", fontSize=8.5,
                                 leading=11.5, textColor=TEXT_MUTED, alignment=TA_CENTER)
S["toc0"] = ParagraphStyle("TOC0", fontName="FreeSerif-Bold", fontSize=11.5,
                           leading=20, textColor=TEXT_PRIMARY, leftIndent=6)
S["toc1"] = ParagraphStyle("TOC1", fontName="FreeSerif", fontSize=10, leading=16,
                           textColor=TEXT_MUTED, leftIndent=26)

# ── TOC document template with body-page detection ─────────────────────────
class KejaDocTemplate(SimpleDocTemplate):
    """afterFlowable feeds TOCEntry tuples (with clickable key); the
    body-start marker lets the footer switch roman -> arabic numbering."""

    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        self.body_start = None

    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))
        if getattr(flowable, "is_body_start", False):
            self.body_start = self.page


def _roman(n: int) -> str:
    vals = [(10, "x"), (9, "ix"), (5, "v"), (4, "iv"), (1, "i")]
    out = ""
    for v, sym in vals:
        while n >= v:
            out += sym
            n -= v
    return out


def make_painter(title: str, footer_left: str):
    """Header (title + accent rule) and footer (author + page number).
    Page 1 of the body PDF is the TOC -> roman; content -> arabic from 1."""
    def painter(canv, doc):
        canv.saveState()
        # header
        canv.setFont("FreeSerif", 7.5)
        canv.setFillColor(TEXT_MUTED)
        canv.drawString(MARGIN, PAGE_H - 0.55 * inch, title.upper())
        canv.setStrokeColor(ACCENT)
        canv.setLineWidth(1.2)
        canv.line(MARGIN, PAGE_H - 0.63 * inch, PAGE_W - MARGIN, PAGE_H - 0.63 * inch)
        # footer
        canv.setStrokeColor(BORDER)
        canv.setLineWidth(0.5)
        canv.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
        canv.setFont("FreeSerif", 7.5)
        canv.setFillColor(TEXT_MUTED)
        canv.drawString(MARGIN, 0.45 * inch, footer_left)
        body_start = doc.body_start
        if body_start is not None and doc.page >= body_start:
            label = str(doc.page - body_start + 1)
        else:
            label = _roman(doc.page)
        canv.drawRightString(PAGE_W - MARGIN, 0.45 * inch, label)
        canv.restoreState()
    return painter


# ── Building blocks ─────────────────────────────────────────────────────────
def heading(text: str, level: int = 0, chapter: str | None = None):
    """H1/H2/H3 with TOC bookmark. level 0 = chapter, 1 = section, 2 = sub."""
    style = S["h1"] if level == 0 else (S["h2"] if level == 1 else S["h3"])
    label = f"{chapter}&nbsp;&nbsp;{text}" if chapter else text
    key = "h_" + hashlib.md5(f"{level}-{chapter}-{text}".encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/><b>{label}</b>', style)
    p.bookmark_name = key
    p.bookmark_level = min(level, 1)
    p.bookmark_text = f"{chapter} {text}" if chapter else text
    p.bookmark_key = key
    return p


def h1_block(text: str, chapter: str | None = None, first_para=None):
    """H1 + accent underline (+ optional first paragraph), orphan-protected."""
    items = [heading(text, 0, chapter),
             HRFlowable(width="100%", color=ACCENT, thickness=1.5,
                        spaceBefore=0, spaceAfter=10)]
    if first_para is not None:
        items.append(first_para)
    return [CondPageBreak(H1_ORPHAN), KeepTogether(items)]


def h2_block(text: str, first=None):
    items = [heading(text, 1)]
    if first is not None:
        items.append(first)
    return [CondPageBreak(70), KeepTogether(items)]


def _bind_dashes(t: str) -> str:
    """Closed em-dash style (word—word, Chicago): the dash lives inside a
    word unit so it can never start a line (ReportLab splits on \\xa0, so
    &nbsp; binding does not work)."""
    return t.replace(" — ", "—").replace(" —", "—").replace("— ", "—")


def body(text: str) -> Paragraph:
    return Paragraph(_bind_dashes(text), S["body"])


def lead(text: str) -> Paragraph:
    return Paragraph(_bind_dashes(text), S["lead"])


def bullets(items: list[str]) -> list:
    return [Paragraph("<bullet>&bull;</bullet>" + _bind_dashes(t), S["bullet"]) for t in items]


def callout_row(stats: list[tuple[str, str]]) -> Table:
    """Row of stat CalloutBoxes: [(big, label), ...] — data-to-ink rule."""
    n = len(stats)
    gap = 10
    w = (AVAIL_W - gap * (n - 1)) / n
    cells, widths = [], []
    for i, (big, label) in enumerate(stats):
        box = Table([[Paragraph(f"<b>{big}</b>", S["stat"])],
                     [Paragraph(label, S["stat_label"])]], colWidths=[w])
        box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), SECTION_BG),
            ("BOX", (0, 0), (-1, -1), 1, ACCENT),
            ("TOPPADDING", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, -1), (-1, -1), 9),
            ("TOPPADDING", (0, -1), (-1, -1), 2),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        cells.append(box)
        widths.append(w)
        if i < n - 1:
            cells.append("")
            widths.append(gap)
    outer = Table([cells], colWidths=widths, hAlign="CENTER")
    outer.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return outer


def quote_box(text: str) -> Table:
    q = Table([[Paragraph(_bind_dashes(text), S["quote"])]], colWidths=[AVAIL_W * 0.92], hAlign="CENTER")
    q.setStyle(TableStyle([
        ("LINEBEFORE", (0, 0), (0, -1), 2.5, ACCENT),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return q


def make_table(header: list[str], rows: list[list], ratios: list[float] | None = None,
               caption: str | None = None, font: float = 9.5, repeat: bool = True):
    """Paragraph-wrapped, centered, palette-coloured table (overflow-safe)."""
    ncols = len(header)
    if ratios is None:
        ratios = [1.0 / ncols] * ncols
    total = sum(ratios)
    widths = [r / total * AVAIL_W for r in ratios]
    assert abs(sum(widths) - AVAIL_W) < 1.0
    th = ParagraphStyle("th_x", parent=S["th"], fontSize=font)
    td = ParagraphStyle("td_x", parent=S["td"], fontSize=font)
    data = [[Paragraph(f"<b>{h}</b>", th) for h in header]]
    for row in rows:
        data.append([Paragraph(_bind_dashes(str(c)), td) for c in row])
    t = Table(data, colWidths=widths, hAlign="CENTER",
              repeatRows=1 if repeat else 0)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 12), t]
    if caption:
        out += [Spacer(1, 4), Paragraph(caption, S["caption"])]
    out.append(Spacer(1, 10))
    return out


def code_block(text: str) -> Paragraph:
    return Paragraph(text.replace("\n", "<br/>").replace(" ", "&nbsp;"), S["code"])


def build_doc(story: list, out_path: str, title: str, subject: str,
              footer_left: str = "Keja AI · A Chacadom Investments venture"):
    """Standard build: TOC page -> PageBreak -> content. multiBuild for TOC."""
    toc = TableOfContents()
    toc.levelStyles = [S["toc0"], S["toc1"]]
    toc.dotsMinLevel = 0
    front = [Paragraph("<b>Table of Contents</b>", S["h1"]),
             HRFlowable(width="100%", color=ACCENT, thickness=1.5,
                        spaceBefore=0, spaceAfter=14),
             toc, PageBreak()]
    doc = KejaDocTemplate(out_path, pagesize=A4,
                          leftMargin=MARGIN, rightMargin=MARGIN,
                          topMargin=MARGIN, bottomMargin=MARGIN,
                          title=title, author="Z.ai", creator="Z.ai", subject=subject)
    painter = make_painter(title, footer_left)
    doc.multiBuild(front + story, onFirstPage=painter, onLaterPages=painter)
    return out_path


def mark_body_start(story: list):
    """Attach the body-start flag to the first heading (recursing into
    KeepTogether wrappers) so the footer can switch roman -> arabic."""
    def find(fl):
        if hasattr(fl, "bookmark_name"):
            return fl
        for inner in getattr(fl, "_content", []):
            found = find(inner)
            if found is not None:
                return found
        return None

    for fl in story:
        if isinstance(fl, CondPageBreak):
            continue
        target = find(fl)
        if target is not None:
            target.is_body_start = True
            return


# ── Cover pipeline (Template 01 — HUD Data Terminal, light) ─────────────────
COVER_CSS = """
@page { size: 794px 1123px; margin: 0; }
:root {
  --c-bg: #eff0f1; --c-accent: #3681a6; --c-text: #1a1b1c;
  --c-muted: #6f7578; --c-mid: #334650; --c-surface: #e4e7e8;
}
html, body { margin: 0; padding: 0; width: 794px; height: 1123px;
  background: var(--c-bg); font-family: 'FreeSerif', Georgia, serif; }
@media screen {
  html { height: auto; display: flex; justify-content: center; min-height: 100vh; background: var(--c-bg); }
  body { transform-origin: top center; scale: min(1, calc(100vw / 794)); margin: 0 auto; }
}
.cover { position: relative; width: 794px; height: 1123px;
  border: none; outline: none; box-shadow: none; }
.layer1 { position: absolute; inset: 0; overflow: hidden; z-index: 1; }
.grid-bg { position: absolute; inset: 0;
  background-image:
    linear-gradient(to right, rgba(51,70,80,0.03) 0.5px, transparent 0.5px),
    linear-gradient(to bottom, rgba(51,70,80,0.03) 0.5px, transparent 0.5px);
  background-size: 50px 50px; }
.layer2 { position: absolute; inset: 0; z-index: 2; }
.anchor-line { position: absolute; left: 95px; top: 112px; bottom: 112px;
  width: 8px; background: var(--c-mid); }
.layer3 { position: absolute; inset: 0; z-index: 3; }
.kicker { position: absolute; left: 185px; top: 168px; width: 500px;
  font-size: 16pt; font-family: 'Inter', 'FreeSerif', sans-serif;
  letter-spacing: 3pt; text-transform: uppercase; color: var(--c-accent);
  opacity: 0.75; font-weight: 400; }
.hero { position: absolute; left: 185px; top: 320px; width: 530px;
  font-size: 64pt; font-weight: 900; line-height: 1.15; color: var(--c-text);
  letter-spacing: 1px; font-family: 'Inter', 'FreeSerif', sans-serif; }
.hero .thin { font-weight: 300; color: var(--c-mid); }
.summary { position: absolute; left: 185px; top: 565px; width: 476px;
  font-size: 16.5pt; line-height: 1.6; color: var(--c-text); opacity: 0.85; }
.meta { position: absolute; left: 185px; top: 845px; width: 500px;
  font-size: 18pt; line-height: 1.55; color: var(--c-text); }
.meta .lbl { color: var(--c-muted); font-size: 13pt; letter-spacing: 2pt;
  text-transform: uppercase; font-family: 'Inter', 'FreeSerif', sans-serif; }
.footer { position: absolute; left: 185px; bottom: 132px; width: 500px;
  font-size: 16pt; letter-spacing: 3pt; text-transform: uppercase;
  color: var(--c-muted); opacity: 0.6; font-family: 'Inter', 'FreeSerif', sans-serif; }
"""

COVER_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700;900&family=Playfair+Display:wght@400;700;900&display=swap" rel="stylesheet">
<style>{css}</style>
</head>
<body>
<div class="cover">
  <div class="layer1"><div class="grid-bg"></div></div>
  <div class="layer2"><div class="anchor-line"></div></div>
  <div class="layer3">
    <div class="kicker">{kicker}</div>
    <div class="hero">{hero}</div>
    <div class="summary">{summary}</div>
    <div class="meta">{meta}</div>
    <div class="footer">{footer}</div>
  </div>
</div>
</body>
</html>
"""


def write_cover(path: str, kicker: str, hero: str, summary: str, meta: str,
                footer: str = "Keja AI &nbsp;·&nbsp; keja.app"):
    html = COVER_HTML.format(css=COVER_CSS, kicker=kicker, hero=hero,
                             summary=summary, meta=meta, footer=footer)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


def render_cover(html_path: str, pdf_path: str):
    subprocess.run(["node", os.path.join(PDF_SKILL_DIR, "scripts", "html2poster.js"),
                    html_path, "--output", pdf_path, "--width", "794px"], check=True)
    return pdf_path


def merge_cover(cover_pdf: str, body_pdf: str, out_pdf: str, title: str,
                subject: str):
    from pypdf import PdfReader, PdfWriter
    A4_W, A4_H = 595.28, 841.89

    def norm(page):
        w, h = float(page.mediabox.width), float(page.mediabox.height)
        if abs(w - A4_W) > 0.3 or abs(h - A4_H) > 0.3:
            page.scale_to(A4_W, A4_H)
        return page

    writer = PdfWriter()
    writer.add_page(norm(PdfReader(cover_pdf).pages[0]))
    for page in PdfReader(body_pdf).pages:
        writer.add_page(norm(page))
    writer.add_metadata({"/Title": title, "/Author": "Z.ai", "/Creator": "Z.ai",
                         "/Subject": subject})
    with open(out_pdf, "wb") as f:
        writer.write(f)
    return out_pdf
